begin;

create type public.user_role as enum ('student', 'teacher', 'admin');
create type public.teacher_profile_status as enum (
  'draft',
  'pending',
  'published',
  'suspended'
);
create type public.verification_status as enum (
  'unverified',
  'pending',
  'verified'
);
create type public.request_status as enum (
  'draft',
  'open',
  'matched',
  'closed',
  'cancelled'
);
create type public.match_status as enum (
  'suggested',
  'viewed',
  'contacted',
  'dismissed'
);
create type public.inquiry_status as enum (
  'sent',
  'viewed',
  'accepted',
  'declined',
  'expired'
);
create type public.review_status as enum ('pending', 'published', 'rejected');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role public.user_role not null default 'student',
  first_name varchar(100) not null default '',
  last_name varchar(100) not null default '',
  phone varchar(30),
  avatar_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.teacher_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles (id) on delete cascade,
  slug varchar(160) not null unique,
  headline varchar(200) not null default '',
  bio text not null default '',
  hourly_price integer not null check (hourly_price >= 0),
  currency varchar(3) not null default 'ILS' check (char_length(currency) = 3),
  years_experience integer not null default 0 check (years_experience >= 0),
  teaches_online boolean not null default false,
  teaches_in_person boolean not null default false,
  verification_status public.verification_status not null default 'unverified',
  profile_status public.teacher_profile_status not null default 'draft',
  average_rating numeric(3, 2) not null default 0 check (
    average_rating between 0 and 5
  ),
  review_count integer not null default 0 check (review_count >= 0),
  response_rate numeric(5, 2) not null default 0 check (
    response_rate between 0 and 100
  ),
  response_time_minutes integer check (response_time_minutes >= 0),
  is_founder boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create table public.subjects (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.subjects (id) on delete restrict,
  name_he varchar(160) not null,
  name_en varchar(160) not null,
  slug varchar(160) not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (parent_id is null or parent_id <> id)
);

create table public.levels (
  id bigint generated by default as identity primary key,
  name_he varchar(160) not null,
  name_en varchar(160) not null,
  slug varchar(160) not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cities (
  id bigint generated by default as identity primary key,
  name_he varchar(160) not null,
  name_en varchar(160) not null,
  slug varchar(160) not null unique,
  latitude numeric(9, 6) check (latitude between -90 and 90),
  longitude numeric(9, 6) check (longitude between -180 and 180),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.teacher_subjects (
  teacher_id uuid not null references public.teacher_profiles (id) on delete cascade,
  subject_id bigint not null references public.subjects (id) on delete restrict,
  experience_years integer check (experience_years >= 0),
  description text,
  primary key (teacher_id, subject_id)
);

create table public.teacher_levels (
  teacher_id uuid not null references public.teacher_profiles (id) on delete cascade,
  level_id bigint not null references public.levels (id) on delete restrict,
  primary key (teacher_id, level_id)
);

create table public.teacher_service_areas (
  teacher_id uuid not null references public.teacher_profiles (id) on delete cascade,
  city_id bigint not null references public.cities (id) on delete restrict,
  primary key (teacher_id, city_id)
);

create table public.teacher_availability (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references public.teacher_profiles (id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  timezone varchar(100) not null default 'Asia/Jerusalem',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (start_time < end_time),
  unique (teacher_id, day_of_week, start_time, end_time)
);

create table public.student_requests (
  id uuid primary key default gen_random_uuid(),
  student_id uuid references public.profiles (id) on delete set null,
  subject_id bigint not null references public.subjects (id) on delete restrict,
  level_id bigint references public.levels (id) on delete restrict,
  city_id bigint references public.cities (id) on delete restrict,
  online_ok boolean not null default false,
  in_person_ok boolean not null default false,
  budget_min integer check (budget_min >= 0),
  budget_max integer check (budget_max >= 0),
  goal text not null check (char_length(btrim(goal)) > 0),
  notes text,
  status public.request_status not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (online_ok or in_person_ok),
  check (budget_min is null or budget_max is null or budget_min <= budget_max)
);

create table public.matches (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.student_requests (id) on delete cascade,
  teacher_id uuid not null references public.teacher_profiles (id) on delete cascade,
  score numeric(5, 2) not null check (score between 0 and 100),
  rank integer not null check (rank > 0),
  subject_score numeric(5, 2) not null check (subject_score between 0 and 100),
  availability_score numeric(5, 2) not null check (
    availability_score between 0 and 100
  ),
  location_score numeric(5, 2) not null check (location_score between 0 and 100),
  budget_score numeric(5, 2) not null check (budget_score between 0 and 100),
  quality_score numeric(5, 2) not null check (quality_score between 0 and 100),
  status public.match_status not null default 'suggested',
  created_at timestamptz not null default now(),
  unique (request_id, teacher_id),
  unique (request_id, rank)
);

create table public.inquiries (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles (id) on delete cascade,
  teacher_id uuid not null references public.teacher_profiles (id) on delete cascade,
  request_id uuid references public.student_requests (id) on delete set null,
  message text not null check (char_length(btrim(message)) > 0),
  status public.inquiry_status not null default 'sent',
  created_at timestamptz not null default now(),
  viewed_at timestamptz,
  responded_at timestamptz,
  check (viewed_at is null or viewed_at >= created_at),
  check (responded_at is null or responded_at >= created_at)
);

create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles (id) on delete cascade,
  teacher_id uuid not null references public.teacher_profiles (id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  body text,
  status public.review_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, teacher_id)
);

create table public.favorites (
  student_id uuid not null references public.profiles (id) on delete cascade,
  teacher_id uuid not null references public.teacher_profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (student_id, teacher_id)
);

create index teacher_profiles_status_idx
  on public.teacher_profiles (profile_status, verification_status);
create index subjects_parent_sort_idx
  on public.subjects (parent_id, sort_order);
create index levels_sort_idx on public.levels (sort_order) where is_active;
create index cities_name_he_idx on public.cities (name_he) where is_active;
create index teacher_subjects_subject_idx on public.teacher_subjects (subject_id);
create index teacher_levels_level_idx on public.teacher_levels (level_id);
create index teacher_service_areas_city_idx on public.teacher_service_areas (city_id);
create index teacher_availability_lookup_idx
  on public.teacher_availability (teacher_id, day_of_week) where is_active;
create index student_requests_student_status_idx
  on public.student_requests (student_id, status, created_at desc);
create index student_requests_subject_status_idx
  on public.student_requests (subject_id, status, created_at desc);
create index student_requests_level_idx on public.student_requests (level_id);
create index student_requests_city_idx on public.student_requests (city_id);
create index matches_teacher_idx on public.matches (teacher_id, status);
create index inquiries_request_idx on public.inquiries (request_id);
create index inquiries_student_status_idx
  on public.inquiries (student_id, status, created_at desc);
create index inquiries_teacher_status_idx
  on public.inquiries (teacher_id, status, created_at desc);
create index reviews_teacher_status_idx
  on public.reviews (teacher_id, status, created_at desc);
create index favorites_teacher_idx on public.favorites (teacher_id);

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger teacher_profiles_set_updated_at
before update on public.teacher_profiles
for each row execute function public.set_updated_at();

create trigger subjects_set_updated_at
before update on public.subjects
for each row execute function public.set_updated_at();

create trigger levels_set_updated_at
before update on public.levels
for each row execute function public.set_updated_at();

create trigger cities_set_updated_at
before update on public.cities
for each row execute function public.set_updated_at();

create trigger teacher_availability_set_updated_at
before update on public.teacher_availability
for each row execute function public.set_updated_at();

create trigger student_requests_set_updated_at
before update on public.student_requests
for each row execute function public.set_updated_at();

create trigger reviews_set_updated_at
before update on public.reviews
for each row execute function public.set_updated_at();

create function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, first_name, last_name)
  values (
    new.id,
    left(coalesce(new.raw_user_meta_data ->> 'first_name', ''), 100),
    left(coalesce(new.raw_user_meta_data ->> 'last_name', ''), 100)
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

insert into public.profiles (id, first_name, last_name)
select
  id,
  left(coalesce(raw_user_meta_data ->> 'first_name', ''), 100),
  left(coalesce(raw_user_meta_data ->> 'last_name', ''), 100)
from auth.users
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.teacher_profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.levels enable row level security;
alter table public.cities enable row level security;
alter table public.teacher_subjects enable row level security;
alter table public.teacher_levels enable row level security;
alter table public.teacher_service_areas enable row level security;
alter table public.teacher_availability enable row level security;
alter table public.student_requests enable row level security;
alter table public.matches enable row level security;
alter table public.inquiries enable row level security;
alter table public.reviews enable row level security;
alter table public.favorites enable row level security;

alter default privileges in schema public
  revoke all on tables from anon, authenticated;
alter default privileges in schema public
  revoke all on sequences from anon, authenticated;
alter default privileges in schema public
  revoke execute on functions from public, anon, authenticated;
alter default privileges in schema public
  grant all on tables to service_role;
alter default privileges in schema public
  grant usage, select on sequences to service_role;

revoke all on table
  public.profiles,
  public.teacher_profiles,
  public.subjects,
  public.levels,
  public.cities,
  public.teacher_subjects,
  public.teacher_levels,
  public.teacher_service_areas,
  public.teacher_availability,
  public.student_requests,
  public.matches,
  public.inquiries,
  public.reviews,
  public.favorites
from anon, authenticated;

grant all on table
  public.profiles,
  public.teacher_profiles,
  public.subjects,
  public.levels,
  public.cities,
  public.teacher_subjects,
  public.teacher_levels,
  public.teacher_service_areas,
  public.teacher_availability,
  public.student_requests,
  public.matches,
  public.inquiries,
  public.reviews,
  public.favorites
to service_role;

grant usage, select on all sequences in schema public to service_role;
revoke execute on function public.set_updated_at() from public, anon, authenticated;
revoke execute on function public.handle_new_auth_user() from public, anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'teacher-avatars',
    'teacher-avatars',
    false,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp']
  ),
  (
    'teacher-gallery',
    'teacher-gallery',
    false,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp']
  )
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

commit;